// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GreetingProvider.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Sila2.Org.Silastandard.Examples.Greetingprovider.V1 {
  public static partial class GreetingProvider
  {
    static readonly string __ServiceName = "sila2.org.silastandard.examples.greetingprovider.v1.GreetingProvider";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Parameters> __Marshaller_sila2_org_silastandard_examples_greetingprovider_v1_SayHello_Parameters = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Parameters.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Responses> __Marshaller_sila2_org_silastandard_examples_greetingprovider_v1_SayHello_Responses = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Responses.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Parameters> __Marshaller_sila2_org_silastandard_examples_greetingprovider_v1_Get_StartYear_Parameters = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Parameters.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Responses> __Marshaller_sila2_org_silastandard_examples_greetingprovider_v1_Get_StartYear_Responses = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Responses.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Parameters, global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Responses> __Method_SayHello = new grpc::Method<global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Parameters, global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Responses>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_sila2_org_silastandard_examples_greetingprovider_v1_SayHello_Parameters,
        __Marshaller_sila2_org_silastandard_examples_greetingprovider_v1_SayHello_Responses);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Parameters, global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Responses> __Method_Get_StartYear = new grpc::Method<global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Parameters, global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Responses>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Get_StartYear",
        __Marshaller_sila2_org_silastandard_examples_greetingprovider_v1_Get_StartYear_Parameters,
        __Marshaller_sila2_org_silastandard_examples_greetingprovider_v1_Get_StartYear_Responses);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.GreetingProviderReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GreetingProvider</summary>
    [grpc::BindServiceMethod(typeof(GreetingProvider), "BindService")]
    public abstract partial class GreetingProviderBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Responses> SayHello(global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Parameters request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Responses> Get_StartYear(global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Parameters request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GreetingProvider</summary>
    public partial class GreetingProviderClient : grpc::ClientBase<GreetingProviderClient>
    {
      /// <summary>Creates a new client for GreetingProvider</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public GreetingProviderClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GreetingProvider that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public GreetingProviderClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected GreetingProviderClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected GreetingProviderClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Responses SayHello(global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Parameters request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Responses SayHello(global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Parameters request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Responses> SayHelloAsync(global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Parameters request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Responses> SayHelloAsync(global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Parameters request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Responses Get_StartYear(global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Parameters request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Get_StartYear(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Responses Get_StartYear(global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Parameters request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Get_StartYear, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Responses> Get_StartYearAsync(global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Parameters request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Get_StartYearAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Responses> Get_StartYearAsync(global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Parameters request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Get_StartYear, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override GreetingProviderClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GreetingProviderClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(GreetingProviderBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHello, serviceImpl.SayHello)
          .AddMethod(__Method_Get_StartYear, serviceImpl.Get_StartYear).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GreetingProviderBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SayHello, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Parameters, global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.SayHello_Responses>(serviceImpl.SayHello));
      serviceBinder.AddMethod(__Method_Get_StartYear, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Parameters, global::Sila2.Org.Silastandard.Examples.Greetingprovider.V1.Get_StartYear_Responses>(serviceImpl.Get_StartYear));
    }

  }
}
#endregion
